/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allSidebar: [{ type: "autogenerated", dirName: "." }],

  embedSidebar: [
    {
      type: "autogenerated",
      dirName: "embed",
    },
  ],

  emailVerificationLibrarySidebar: [
    {
      type: "autogenerated",
      dirName: "email-verification-library",
    },
  ],

  openApiSidebar: [
    {
      type: "category",
      label: "API",

      link: {
        type: "generated-index",
        title: "API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "docs/api",
      },
      // @ts-ignore
      items: require("./docs/api/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
