// @ts-nocheck

const apiSidebar = require('./docs/api/sidebar.js').filter(
  (item) => item.id !== 'api/introduction'
);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allSidebar: [{ type: 'autogenerated', dirName: '.' }],

  embedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'embed',
    },
  ],

  emailVerificationLibrarySidebar: [
    {
      type: 'autogenerated',
      dirName: 'email-verification-library',
    },
  ],

  openApiSidebar: [
    {
      type: 'category',
      label: 'API Reference',

      link: {
        type: 'generated-index',
        title: 'API Reference',
        description:
          "Welcome to the Pingback API documentation! Let's get started:",
        slug: 'api',
      },
      items: [
        { type: 'doc', id: 'api/introduction' }, // Ensure 'Introduction' is first
        { type: 'doc', id: 'api/glossary', label: 'Glossary' },
        { type: 'doc', id: 'api/errors', label: 'Errors' },
        ...apiSidebar,
      ],
    },
  ],
};

module.exports = sidebars;
